### ISSUE TITLE
Can't create event!

### ISSUE THREAD

**Issue by meadch** [shelmsoptions/event#1]
Repro steps:

1. Register or login
2. Create a new event
3. Observe validation errors that appear to include to user validation errors:

```
["User must exist", "Name can't be blank", "Location can't be blank", "Location state can't be blank", "Date can't be blank"]
```

Expectation:

Expected to see new event in table after submitting form.

**Comment by shelmsoptions** [comment]
corrected:
private params in events controller - was missing require: '.require(:event)'     (params.xxxx(xxxxx).permit)
